### ISSUE TITLE
Linux boot failed on nSIM_arc700

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/linux#12]
Boot linux failed on nSIM_arc700, see full log here: [nSIM_failed_boot_log.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/linux/files/3363014/nSIM_failed_boot_log.txt).
```
Freeing unused kernel memory: 2200K
This architecture does not have kernel memory protection.
Run /init as init process
potentially unexpected fatal signal 7.
Path: /bin/busybox
CPU: 0 PID: 1 Comm: init Not tainted 5.2.0-rc7 #2

[ECR   ]: 0x00230200 => Write access not allowed on page
[EFA   ]: 0x20007ec8
[BLINK ]: 0x20003eea
[ERET  ]: 0x20003f5e
    @off 0x3f5e in [/lib/ld-uClibc-1.0.31.so]
    VMA: 0x20000000 to 0x20006000
[STAT32]: 0x00000886 : U         E2 E1 
BTA: 0x200027a4	 SP: 0x5fbcbd70	 FP: 0x00000000
LPS: 0x20003f52	LPE: 0x20003f62	LPC: 0x00000020
r00: 0x00000020	r01: 0x200010f4	r02: 0x20001280	
r03: 0x00000180	r04: 0x0000000c	r05: 0x00000000	
r06: 0x20007ec8	r07: 0x00000000	r08: 0x00001000	
r09: 0x00000000	r10: 0x00000000	r11: 0x00000000	
r12: 0x200010f4	r13: 0x20000000	r14: 0x5fbcbf20	
r15: 0x5fbcbf14	r16: 0x5fbcbde8	r17: 0x00000000	
r18: 0x00000000	r19: 0x00000000	r20: 0x00000000	
r21: 0x00000000	r22: 0x00000000	r23: 0x00000000	
r24: 0x00000000	r25: 0x00000000	


Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000007
---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000007 ]---
```

Build linux from:
Build from: _https://git.kernel.org/pub/scm/linux/kernel/git/vgupta/arc.git_
Commit: _5c100a5d62455a9703a8106d1c6532e9c60628df_

Path to vmlinux: _/remote/ru20home1/falaleev/saved_binary/vmlinux_nSIM_arc700.5c100a5d62455a9703a8106d1c6532e9c60628df.2019-07-05_10-51-02_Hb.bu_gcc_upstr.uclibc_
Path to rootf: _/remote/ru20home1/falaleev/saved_binary/rootfs_nSIM_arc700.5c100a5d62455a9703a8106d1c6532e9c60628df.2019-07-05_10-51-02_Hb.bu_gcc_upstr.uclibc.cpio_

**Comment by vineetgarc** [comment]
Thx for the report. In my low level irq rework one of the interim commits 6c5b01c2ed25 was broken for ARC700. I've fixed it in place and force pushed for-curr
