### ISSUE TITLE
[ARC64] kernel panic with compressed initramfs

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/linux#25]
ARC64 port of Linux kernel panics when unpacking a **compressed** initramfs.
```
unpack rootfs image as initramfs...
random: fast init done
unpack initramfs done !
Kernel panic - not syncing: broken padding
---[ end Kernel panic - not syncing: broken padding ]---
```

broken system needs to have atleast
```
CONFIG_INITRAMFS_COMPRESSION_GZIP=y
# CONFIG_INITRAMFS_COMPRESSION_NONE is not set
```
I've not tried other compression methods:

Works fine for
```
CONFIG_INITRAMFS_COMPRESSION_NONE=y
```

This is very likely a gcc codegen issue of some sort

Tested with 
Linux 5.6: 2020-06-23 9a3356b1e857 ARCv3: entry: hw auto-save need not save code-density base regs  
gcc: 2020-06-22 90a22db1ffcb arc64:fix crtstuff to use proper 64bit pointers
binutils: 2020-06-23 a6f7e63b49a4 arc64: fix ldl flag format

**Comment by abrodkin** [comment]
@vineetgarc I suggest to re-assign it to @claziss due to your guess about codegen and one we get regression testing for ARC64 in place we'll see if it's still relevant, OK?

**Comment by vineetgarc** [comment]
@abrodkin gcc folks generally require a test case of failing file - as of now we don't what exact place the failure is happening (remeber paddelfish bringup issue you and @Palmyr3 chased). So it will have to be someone else to dig down to exact failure point. Perhaps solicit volunteers @shahab-vahedi @cupertinomiranda to get their feet muddy in ARC64

**Comment by cupertinomiranda** [comment]
@abrodkin Up until you find what is the the incorrect generated code it is to my eyes your problem. I had enough of this unjustified muddy work ... to be "politically" correct.
@vineetgarc I have mud to my neck at the moment, luckily feet are on solid ground ... otherwise !!!!

**Comment by vineetgarc** [comment]
Retested this today with latest nSIM and gcc (2020-07-29 f470b90af0b3 arc64: fix tls detection in assembler) and it works now. So it must have been one of the fixed issues in gcc / nSIM etc. 

```
Bringing up loopback device
ifconfig: SIOCSIFHWADDR: No such device
Mounting Posix Mqueue filesys
Linux version 5.6.0-00099-g02607ba8cf78 (vineetg@vineetg-Latitude-7400) (gcc version 10.1.1 20200701 (GCC)) #94 PREEMPT Tue Aug 4 19:40:28 PDT 2020
CONFIG_INITRAMFS_SOURCE="~/arc/RAMFS/ramfs_2008-arc64-static"
***********************************************************************
			Welcome to ARCLinux
***********************************************************************
[ARCLinux]# 
[ARCLinux]# 
[ARCLinux]# zcat /proc/config.gz | grep RAMFS
CONFIG_INITRAMFS_SOURCE="~/arc/RAMFS/ramfs_2008-arc64-static"
CONFIG_INITRAMFS_ROOT_UID=0
CONFIG_INITRAMFS_ROOT_GID=0
CONFIG_INITRAMFS_COMPRESSION_GZIP=y
# CONFIG_INITRAMFS_COMPRESSION_BZIP2 is not set
# CONFIG_INITRAMFS_COMPRESSION_LZMA is not set
# CONFIG_INITRAMFS_COMPRESSION_XZ is not set
# CONFIG_INITRAMFS_COMPRESSION_LZO is not set
# CONFIG_INITRAMFS_COMPRESSION_LZ4 is not set
# CONFIG_INITRAMFS_COMPRESSION_NONE is not set

[ARCLinux]# 
```
