### ISSUE TITLE
Is there a  plan to  add the support for the arch of HS48FS into the builderoot-demos repository?

### ISSUE THREAD

**Issue by setvensxiong** [foss-for-synopsys-dwc-arc-processors/linux#29]
There is a buildroot-demos in the GIT repository, which is very cool and can compile the kernel, bootloader, root filesystem, cross-compile tool chain all at once, but the buildroot-demos  only supports ARCHs like ARC 750D, ARC 770D, ARC HS38.
It's hoped that the support for the arch of HS48FS would also be added into the builderoot-demos repository.
Thanks!

**Comment by abrodkin** [comment]
If you provide an explanation on what do you expect to be done specially for HS48FS we may consider doing that.
Now from software development standpoint HS48FS doesn't differ from an ordinary HS48 if safety features are disabled (I guess that's exactly your case). So whatever works for normal HS48 will work for your HS48FS.

Also note, in our https://github.com/foss-for-synopsys-dwc-arc-processors/buildroot-demos repo we keep just a couple of demos which could be implemented on our development boards. I.e. there're much more interesting things which could be built and run but we never planned to build and run everything.

So getting back to your question: if you're just wondering how to build your own Linux "distribution" for ARC HS48x2FS with help of Buildroot
1. Prepare a Linux kernel BSP for your platform (similarly to what we do in `arch/arc/plat-xxx` folders, for example for HSDK: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arc/plat-hsdk) and corresponding configuration file (again an example from HSDK - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arc/configs/hsdk_defconfig).
2. Configure Buildroot to fetch the Linux kernel from your own Git repository
3. Select "ARC HS38 with Quad MAC & FPU" in target settings
3. Select needed packages
4. Build and deploy your image/file-system

Oh, and by the way please look at the upstream Buildroot repository (https://git.buildroot.org/buildroot/) where we have all the recent changes and improvements, while in our "fork" we only keep some "snapshots" used for particular demos.

Please let me know if that answer helps or you need more clarifications on that.

**Comment by setvensxiong** [comment]
Thanks for your nice comments. I have got all I want to know from these comments.
