### ISSUE TITLE
use openamp on HS CPU base on linux

### ISSUE THREAD

**Issue by joshualin-petaio** [foss-for-synopsys-dwc-arc-processors/linux#73]
Hi,

We need to use openamp on HS CPU base on linux to communicate with others CPU.
Now we can run the linux.
How can I import the openamp and use it ?
Does there have document or something else can help me ?

Joshua

**Comment by abrodkin** [comment]
@joshualin-petaio I'm wondering if something is still needs to be done here or the issue is now solved and we may close it here?

**Comment by joshualin-petaio** [comment]
Hi Alexey,

Openamp is more stable on our environment. So, this issue can close now.

Thanks, Joshua
