### ISSUE TITLE
[linux perf] Implement L2 cache perf counters

### ISSUE THREAD

**Issue by vineetgarc** [foss-for-synopsys-dwc-arc-processors/linux#8]
The L2 cache perf counting is orthogonal to way we do normal cpu counters and thus may require a different driver !

**Comment by vineetgarc** [comment]
I can't seem to find EugeniyP in the members !

**Comment by abrodkin** [comment]
@vineetgarc you wanted to select one @Palmyr3 :)

**Comment by vineetgarc** [comment]
Not doing this for ARCv2 anymore !
